**Ejercicio de Clase: Explorando Matrices y operaciones básicas**

In [3]:
# Paso 1: Importa la librería NumPy como np.
import numpy as np

# Paso 2: Crea una matriz A de 3x3 con números enteros del 1 al 9.
# La consigna pide crearla a partir de una lista de listas.
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Matriz Original A:")
print(A)
print("-" * 30)

# Paso 3: Realiza las siguientes operaciones.
# Suma 10 a cada elemento de la matriz.
suma = A + 10
print("Suma de A + 10:")
print(suma)
print("-" * 30)

# Multiplica la matriz por 2.
multiplicacion = A * 2
print("Multiplicación de A * 2:")
print(multiplicacion)
print("-" * 30)

# Extrae los elementos mayores a 5 utilizando selección condicional.
mayores_a_5 = A[A > 5]
print("Elementos mayores a 5:")
print(mayores_a_5)
print("-" * 30)

# Paso 4: Analiza la diferencia entre asignación (referencia) y copia.

# --- Primer caso: Asignación (B = A) ---
print("Análisis de Asignación (Referencia):")
B = A
# Modifica un valor de "B".
B[0, 0] = 99
print("Matriz B modificada:")
print(B)
print("¿Cambió también A?")
print("Matriz A después de modificar B:")
print(A) # Se observa que "A" también cambió.
print("-" * 30)

# --- Segundo caso: Copia (B = A.copy()) ---
print("Análisis con .copy():")
# Reseteamos "A" a su valor original para una comparación justa.
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = A.copy()
# Modifica un valor de "B".
B[0, 0] = 99
print("Matriz B (copia) modificada:")
print(B)
print("¿Qué ocurrió con A esta vez?")
print("Matriz A después de modificar la copia B:")
print(A) # Se observa que "A" permanece sin cambios.

Matriz Original A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
Suma de A + 10:
[[11 12 13]
 [14 15 16]
 [17 18 19]]
------------------------------
Multiplicación de A * 2:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
------------------------------
Elementos mayores a 5:
[6 7 8 9]
------------------------------
Análisis de Asignación (Referencia):
Matriz B modificada:
[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]
¿Cambió también A?
Matriz A después de modificar B:
[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]
------------------------------
Análisis con .copy():
Matriz B (copia) modificada:
[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]
¿Qué ocurrió con A esta vez?
Matriz A después de modificar la copia B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


**<p style="font-size:18px; color:auto;">Análisis de Copia vs. Referencia</p>**

El último paso del ejercicio demuestra un concepto fundamental de NumPy: la diferencia entre una referencia y una copia de un array.

* **Primer Caso _(Asignación B = A)_:** Cuando ejecutas B = A, no estás creando una nueva matriz. En cambio, estás creando una referencia, lo que significa que tanto A como B apuntan exactamente al mismo objeto en la memoria. Por eso, al modificar B (cambiando el primer elemento a 99), el cambio también se reflejó en A, porque son dos nombres para la misma matriz.

* **Segundo Caso _(Copia B = A.copy())_:** Al usar el método _.copy()_, se crea una copia real e independiente de la matriz A en una nueva ubicación de la memoria. Por lo tanto, A y B son dos objetos completamente separados. Cuando modificaste B esta vez, A no se vio afectada y mantuvo sus valores originales, demostrando que la modificación solo ocurrió en la copia.
