**<p style="font-size:18px; color:auto;">1. Código Fuente y Explicación detallada.</p>**

In [1]:
import numpy as np

# ===================================================================
# 1. Carga y estructuración de datos
# ===================================================================

# Se crea un array de 5x5 con precios de acciones simulados.
# Los precios son enteros aleatorios entre 50 y 200.
# Cada fila representa una acción y cada columna un día de cotización
precios_acciones = np.random.randint(50, 201, size=(5, 5))
print("1. Matriz de precios de acciones (5 acciones, 5 días):")
print(precios_acciones)
print("-" * 50)

# ===================================================================
# 2. Análisis y transformación de datos
# ===================================================================

# Obtención del promedio, valor máximo y mínimo por acción (por fila).
# Usamos las funciones de NumPy a lo largo del eje 1 (columnas) para analizar cada acción.
promedio_por_accion = np.mean(precios_acciones, axis=1)
max_por_accion = np.max(precios_acciones, axis=1)
min_por_accion = np.min(precios_acciones, axis=1)

print("2. Análisis por acción:")
for i in range(len(promedio_por_accion)):
    print(f"  Acción {i+1}: Promedio=${promedio_por_accion[i]:.2f}, Máximo=${max_por_accion[i]}, Mínimo=${min_por_accion[i]}")

# Cálculo de la variación porcentual diaria.
# Variación = (Precio_hoy - Precio_ayer) / Precio_ayer * 100
# Usamos slicing para seleccionar los precios de "ayer" y "hoy".
precios_ayer = precios_acciones[:, :-1]
precios_hoy = precios_acciones[:, 1:]
variacion_diaria = (precios_hoy - precios_ayer) / precios_ayer * 100

print("\nVariación porcentual diaria (%):")
print(variacion_diaria)

# Aplicación de función de normalización (Min-Max) a los datos.
# Normalización = (X - min(X)) / (max(X) - min(X))
# Esto escala los precios de cada acción a un rango entre 0 y 1.
minimos = precios_acciones.min(axis=1, keepdims=True)
maximos = precios_acciones.max(axis=1, keepdims=True)
precios_normalizados = (precios_acciones - minimos) / (maximos - minimos)

print("\nPrecios Normalizados (escala 0 a 1):")
print(precios_normalizados)
print("-" * 50)


# ===================================================================
# 3. Optimización y selección de datos
# ===================================================================

# Extracción del rendimiento de la acción 3 en el día 4.
# Se usa indexación avanzada, similar a la selección de elementos en una matriz.
rendimiento_especifico = precios_acciones[2, 3] # Fila 2 (Acción 3), Columna 3 (Día 4)
print(f"3. Rendimiento de la Acción 3 en el Día 4: ${rendimiento_especifico}")

# Aplicación de broadcasting para sumar un ajuste de mercado a todas las acciones.
# En lugar de un bucle, se suma un escalar directamente a la matriz.
# La operación se aplica a todos los elementos.
ajuste = 5.50
precios_ajustados = precios_acciones + ajuste
print("\nPrecios después de un ajuste de mercado de $5.50 (Broadcasting):")
print(precios_ajustados)
print("-" * 50)

1. Matriz de precios de acciones (5 acciones, 5 días):
[[145  52  60 165  59]
 [ 78 194 159 170 167]
 [125 178 190  85 192]
 [125 198  81 145  69]
 [154 200 130  97 142]]
--------------------------------------------------
2. Análisis por acción:
  Acción 1: Promedio=$96.20, Máximo=$165, Mínimo=$52
  Acción 2: Promedio=$153.60, Máximo=$194, Mínimo=$78
  Acción 3: Promedio=$154.00, Máximo=$192, Mínimo=$85
  Acción 4: Promedio=$123.60, Máximo=$198, Mínimo=$69
  Acción 5: Promedio=$144.60, Máximo=$200, Mínimo=$97

Variación porcentual diaria (%):
[[-64.13793103  15.38461538 175.         -64.24242424]
 [148.71794872 -18.04123711   6.91823899  -1.76470588]
 [ 42.4          6.74157303 -55.26315789 125.88235294]
 [ 58.4        -59.09090909  79.01234568 -52.4137931 ]
 [ 29.87012987 -35.         -25.38461538  46.39175258]]

Precios Normalizados (escala 0 a 1):
[[0.82300885 0.         0.07079646 1.         0.0619469 ]
 [0.         1.         0.69827586 0.79310345 0.76724138]
 [0.37383178 0.869158

**<p style="font-size:18px; color:auto;">2. Análisis Comparativo: NumPy vs. Métodos Tradicionales</p>**

Se analiza la eficiencia de realizar estas tareas sin NumPy, utilizando listas de Python estándar.

* **Estructura y Carga:** Con listas, tendríamos una "lista de listas". La generación de datos aleatorios requeriría bucles anidados y la función _random.randint()_ de Python, que es menos directa que _np.random.randint(low, high, size)_.

* **Cálculos Estadísticos:** Para calcular el promedio o el máximo de cada acción (fila), necesitaríamos escribir bucles for explícitos para iterar sobre cada sublista. NumPy lo resuelve con una sola llamada de función _(np.mean(axis=1))_, que es más legible y significativamente más rápida porque las operaciones se ejecutan en código C compilado.

* **Operaciones Matemáticas:** El cálculo de la variación porcentual sería complejo con listas. Requeriría bucles anidados para acceder al elemento [i][j] y [i][j-1], realizar la resta y la división, y almacenar el resultado en una nueva lista de listas. En NumPy, esta operación se realiza de forma vectorizada en tres líneas de código claras y eficientes.

* **Rendimiento:** La principal ventaja de NumPy es su rendimiento. Las operaciones vectorizadas y el broadcasting permiten realizar cálculos en arreglos completos sin la sobrecarga de los bucles de Python. Para grandes volúmenes de datos, como los que maneja una empresa financiera, la diferencia en velocidad es de órdenes de magnitud.

**<p style="font-size:18px; color:auto;">3. Conclusiones</p>**

La implementación de NumPy es la estrategia correcta para la empresa por las siguientes razones:

* **Eficiencia:** Reduce drásticamente el tiempo de cómputo para operaciones matemáticas y estadísticas en grandes conjuntos de datos.

* **Claridad del Código:** El código es más conciso y legible. Operaciones complejas se expresan en pocas líneas, lo que facilita el mantenimiento.

* **Fundamento del Ecosistema:** NumPy es la base de otras librerías de ciencia de datos como Pandas y Matplotlib. Adoptar NumPy facilita la integración futura de herramientas más avanzadas para el análisis y la visualización de datos.

En resumen, NumPy no solo soluciona el problema actual de rendimiento lento, sino que también establece una base sólida y escalable para el futuro de la herramienta de análisis financiero de la empresa.