**1. Creación y Manipulación de Arrays**

In [2]:
import numpy as np

# Genera un array de 20 números enteros aleatorios entre 1 y 100
# Usamos np.random.randint() para esta tarea.
array_aleatorio = np.random.randint(1, 101, size=20)
print(f"Array original: {array_aleatorio}")

# Calcular la suma, promedio, máximo y mínimo del array
suma = np.sum(array_aleatorio)
promedio = np.mean(array_aleatorio)
maximo = np.max(array_aleatorio)
minimo = np.min(array_aleatorio)

print(f"Suma: {suma}")
print(f"Promedio: {promedio}")
print(f"Máximo: {maximo}")
print(f"Mínimo: {minimo}")

# Ordenar el array en forma ascendente y descendente
ascendente = np.sort(array_aleatorio)
descendente = np.sort(array_aleatorio)[::-1] # Usamos slicing para invertir el array ordenado

print(f"Orden ascendente: {ascendente}")
print(f"Orden descendente: {descendente}")

# Extrae todos los valores pares del array
# Se utiliza la selección condicional que vimos en el manual
pares = array_aleatorio[array_aleatorio % 2 == 0]
print(f"Valores pares: {pares}")

# Reemplaza todos los valores impares por -1
# Creamos una copia para no modificar el original al hacer esto
array_modificado = array_aleatorio.copy()
array_modificado[array_modificado % 2 != 0] = -1
print(f"Array con impares reemplazados: {array_modificado}")

Array original: [39 43 13 70 97 27 20 41 54 94 97 58 48 37 85 43 77 76 21 41]
Suma: 1081
Promedio: 54.05
Máximo: 97
Mínimo: 13
Orden ascendente: [13 20 21 27 37 39 41 41 43 43 48 54 58 70 76 77 85 94 97 97]
Orden descendente: [97 97 94 85 77 76 70 58 54 48 43 43 41 41 39 37 27 21 20 13]
Valores pares: [70 20 54 94 58 48 76]
Array con impares reemplazados: [-1 -1 -1 70 -1 -1 20 -1 54 94 -1 58 48 -1 -1 -1 -1 76 -1 -1]


**2. Operaciones con matrices**

In [3]:
# Crea dos matrices 4x4 de números enteros aleatorios entre 1 y 50
matriz1 = np.random.randint(1, 51, size=(4, 4))
matriz2 = np.random.randint(1, 51, size=(4, 4))

print(f"Matriz 1:\n{matriz1}")
print(f"Matriz 2:\n{matriz2}")

# Realiza la suma, resta y multiplicación matricial
suma_matrices = matriz1 + matriz2
resta_matrices = matriz1 - matriz2
# Para la multiplicación matricial, usamos np.dot() como indica el manual
multiplicacion_matrices = np.dot(matriz1, matriz2)

print(f"Suma de matrices:\n{suma_matrices}")
print(f"Resta de matrices:\n{resta_matrices}")
print(f"Multiplicación matricial:\n{multiplicacion_matrices}")

# Calcula la matriz transpuesta de la primera matriz
transpuesta1 = matriz1.T
print(f"Transpuesta de Matriz 1:\n{transpuesta1}")

# Obtén el determinante de la segunda matriz
determinante2 = np.linalg.det(matriz2)
print(f"Determinante de Matriz 2: {determinante2}")

# Encuentra la inversa de la segunda matriz (si es invertible)
if determinante2 != 0:
    inversa2 = np.linalg.inv(matriz2)
    print(f"Inversa de Matriz 2:\n{inversa2}")
else:
    print("La Matriz 2 no es invertible, su determinante es 0.")

Matriz 1:
[[41  7 47 36]
 [42 25 50  7]
 [36  6 22 29]
 [30  3 12 29]]
Matriz 2:
[[39 49  4 40]
 [28 39  3 27]
 [44 10 22 26]
 [19 41 49 34]]
Suma de matrices:
[[80 56 51 76]
 [70 64 53 34]
 [80 16 44 55]
 [49 44 61 63]]
Resta de matrices:
[[  2 -42  43  -4]
 [ 14 -14  47 -20]
 [ -8  -4   0   3]
 [ 11 -38 -37  -5]]
Multiplicación matricial:
[[4547 4228 2983 4275]
 [4671 3820 1686 3893]
 [3091 3407 2067 3160]
 [2333 2896 1814 2579]]
Transpuesta de Matriz 1:
[[41 42 36 30]
 [ 7 25  6  3]
 [47 50 22 12]
 [36  7 29 29]]
Determinante de Matriz 2: 336379.9999999998
Inversa de Matriz 2:
[[-0.08757952  0.1169808   0.03215114 -0.01444795]
 [-0.08678281  0.13377133 -0.00958737  0.00319876]
 [-0.04705393  0.03820679  0.00984006  0.01749212]
 [ 0.22140436 -0.28174683 -0.02058684  0.00841905]]


**3. Aplicación de funciones en NumPy**

In [4]:
# Genera un array de 100 valores distribuidos uniformemente entre 0 y 10
# La función np.linspace() es perfecta para esto
valores = np.linspace(0, 10, 100)
print(f"Array con 100 valores entre 0 y 10: {valores}")

# Calcula el seno y coseno de cada valor en el array
seno_valores = np.sin(valores)
coseno_valores = np.cos(valores)

print(f"Seno de los valores: {seno_valores}")
print(f"Coseno de los valores: {coseno_valores}")

# Aplica la función exponencial a cada elemento del array
exp_valores = np.exp(valores)
print(f"Exponencial de los valores: {exp_valores}")

# Encuentra la raíz cuadrada de cada elemento mayor a 5 en el array
# Combinamos selección condicional y una función matemática
mayores_a_5 = valores[valores > 5]
raiz_mayores_a_5 = np.sqrt(mayores_a_5)
print(f"Raíz cuadrada de valores mayores a 5: {raiz_mayores_a_5}")

Array con 100 valores entre 0 y 10: [ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7