In [1]:
# Importar la librería NumPy
import numpy as np

# 1. Crear un arreglo con np.arange(1, 17) y redimensionarlo a una matriz de 4x4.
matriz_arange = np.arange(1, 17).reshape(4, 4)
print("1. Matriz 4x4 creada con arange y reshape:")
print(matriz_arange)

print("-" * 40)

# 2. Generar un arreglo de 10 elementos equidistantes entre 0 y 100.
arreglo_linspace = np.linspace(0, 100, 10)
print("2. Arreglo de 10 elementos equidistantes (linspace):")
print(arreglo_linspace)

print("-" * 40)

# 3. Crear una matriz aleatoria de 3x3 con enteros entre 1 y 20.
matriz_aleatoria = np.random.randint(1, 20, size=(3, 3))
print("3. Matriz aleatoria 3x3 de enteros:")
print(matriz_aleatoria)

print("-" * 40)

# 4. Aplicar np.sqrt() y np.log() sobre las matrices creadas.
print("4. Aplicando funciones matemáticas:")

# Raíz cuadrada (sqrt)
print("\nRaíz cuadrada de la primera matriz:")
print(np.sqrt(matriz_arange))

print("\nRaíz cuadrada de la matriz aleatoria:")
print(np.sqrt(matriz_aleatoria))

# Logaritmo natural (log)
print("\nLogaritmo natural de la primera matriz:")
print(np.log(matriz_arange))

print("\nLogaritmo natural de la matriz aleatoria:")
print(np.log(matriz_aleatoria))


print("\nRaíz cuadrada del Arreglo de 10 elementos:")
print(np.sqrt(arreglo_linspace))


1. Matriz 4x4 creada con arange y reshape:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
----------------------------------------
2. Arreglo de 10 elementos equidistantes (linspace):
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]
----------------------------------------
3. Matriz aleatoria 3x3 de enteros:
[[ 1  2 18]
 [ 1  3 17]
 [ 7 12 19]]
----------------------------------------
4. Aplicando funciones matemáticas:

Raíz cuadrada de la primera matriz:
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]
 [3.60555128 3.74165739 3.87298335 4.        ]]

Raíz cuadrada de la matriz aleatoria:
[[1.         1.41421356 4.24264069]
 [1.         1.73205081 4.12310563]
 [2.64575131 3.46410162 4.35889894]]

Logaritmo natural de la primera matriz:
[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.7

## 5. Diferencias al Aplicar Funciones (Enteros vs. Flotantes)
La pregunta final es clave para entender cómo opera NumPy.

Universalidad de la Aplicación: Las funciones matemáticas de NumPy (como np.sqrt y np.log) se aplican elemento por elemento a todo el arreglo, sin importar si sus datos son de tipo entero (int) o de punto flotante (float). No necesitas escribir un código diferente para cada tipo de dato.

El Tipo de Dato del Resultado (dtype): La principal diferencia que se nota está en el tipo de dato del arreglo resultante.

Cuando aplicas una función como np.sqrt o np.log a un arreglo de enteros, NumPy casi siempre devolverá un nuevo arreglo de flotantes (float64).
¿Por qué? Porque el resultado de la operación (ej: la raíz cuadrada de 2 o el logaritmo de 5) generalmente no es un número entero. Para no perder la parte decimal y mantener la precisión del cálculo, NumPy automáticamente "promociona" el tipo de dato a flotante.
En el caso del arreglo creado con np.linspace, como ya es de tipo flotante, el resultado de aplicarle estas funciones seguirá siendo un arreglo de tipo flotante.