In [1]:
# Paso 1: Importar la librería NumPy
import numpy as np

# Paso 2: Crear una matriz A de 3x3 con números del 1 al 9
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print("Matriz A original:")
print(A)
print("-" * 20)

# Paso 3: Realizar las siguientes operaciones

# Sumar 10 a cada elemento de la matriz
suma = A + 10
print("Matriz A + 10:")
print(suma)
print("-" * 20)

# Multiplicar la matriz por 2
multiplicacion = A * 2
print("Matriz A * 2:")
print(multiplicacion)
print("-" * 20)

# Extraer los elementos mayores a 5
mayores_a_5 = A[A > 5]
print("Elementos de A mayores a 5:")
print(mayores_a_5)
print("-" * 20)

# Paso 4: Analizar asignación y copia

# Asignación (B es una referencia a A)
print("Análisis de Asignación (Referencia):")
B = A
# Modificamos un elemento de B
B[0, 0] = 99
print("Matriz B modificada:")
print(B)
print("¿Cambió también A? Sí, porque B es una referencia a A.")
print("Matriz A después de modificar B:")
print(A)
print("-" * 20)

# Para el siguiente paso, restauramos A a su valor original
A[0, 0] = 1

# Copia (B es una copia independiente de A)
print("Análisis de Copia:")
B = A.copy()
# Modificamos un elemento de B
B[0, 0] = 555
print("Matriz B (copia) modificada:")
print(B)
print("¿Cambió también A? No, porque B es una copia independiente.")
print("Matriz A después de modificar la copia B:")
print(A)


Matriz A original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
Matriz A + 10:
[[11 12 13]
 [14 15 16]
 [17 18 19]]
--------------------
Matriz A * 2:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
--------------------
Elementos de A mayores a 5:
[6 7 8 9]
--------------------
Análisis de Asignación (Referencia):
Matriz B modificada:
[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]
¿Cambió también A? Sí, porque B es una referencia a A.
Matriz A después de modificar B:
[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]
--------------------
Análisis de Copia:
Matriz B (copia) modificada:
[[555   2   3]
 [  4   5   6]
 [  7   8   9]]
¿Cambió también A? No, porque B es una copia independiente.
Matriz A después de modificar la copia B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Explicación: ¿Copia o Referencia?
La parte final del ejercicio demuestra una de las características más importantes de NumPy (y de Python en general) al manejar objetos.

Asignación (B = A): Cuando haces B = A, no estás creando una nueva matriz. Simplemente estás creando una nueva "etiqueta" o "apodo" (B) que apunta al mismo objeto en la memoria al que apunta A. Por lo tanto, cualquier cambio que hagas a través de B se reflejará en A (y viceversa), porque ambos nombres se refieren a la misma matriz. A esto se le llama crear una vista o una referencia.

Copia (B = A.copy()): Al usar el método .copy(), estás creando una matriz completamente nueva e independiente en otra ubicación de la memoria, con los mismos valores que A. Como B es ahora un objeto separado, los cambios que realices en B no afectarán en absoluto a la matriz original A.