Casos de uso más comunes y prácticos donde las funciones de matrices son la opción ideal:
==========================================================================================

**<p style="font-size:18px; color:auto;">1. Cuando el Rendimiento es Crítico (Cálculos Numéricos Intensivos)</p>**

Las operaciones con matrices de NumPy son órdenes de magnitud más rápidas que sus equivalentes en Python puro.

**La Razón:** Las funciones de NumPy están escritas en lenguajes de bajo nivel (como C o Fortran) y están optimizadas para ejecutar operaciones en bloques de memoria completos a la vez (un concepto llamado vectorización). Un bucle for de Python, en cambio, procesa cada elemento individualmente, lo cual es mucho más lento.


In [4]:
"""
Ejemplo Práctico: Sumar dos matrices grandes.
"""
import numpy as np
import time

# Creando dos matrices grandes de 1000x1000
matriz_a = np.random.rand(1000, 1000)
matriz_b = np.random.rand(1000, 1000)

# Método NumPy (vectorizado)
start_time = time.time()
resultado_numpy = matriz_a + matriz_b
end_time = time.time()
print(f"Tiempo con NumPy: {end_time - start_time:.6f} segundos")

# Método con bucles for (sería extremadamente lento y no se recomienda ejecutar)
# for i in range(1000):
#     for j in range(1000):
#         resultado_manual[i][j] = matriz_a[i][j] + matriz_b[i][j]

Tiempo con NumPy: 0.002001 segundos


**<p style="font-size:18px; color:auto;">2. Cuando la Simplicidad y Legibilidad del Código son Importantes</p>**

El código que utiliza funciones de matrices es mucho más corto, limpio y fácil de leer porque las operaciones matemáticas se expresan de forma natural.

Comparación Directa:
* Multiplicación de matrices en NumPy: C = A @ B
* Multiplicación de matrices con bucles: Requiere bucles anidados complejos y es fácil cometer errores.

**<p style="font-size:18px; color:auto;">3. Para Álgebra Lineal y Resolución de Sistemas de Ecuaciones</p>**

Este es el caso de uso por excelencia. Si tienes un problema que puede ser modelado por un sistema de ecuaciones lineales, NumPy es la herramienta perfecta

In [5]:
"""
Ejemplo Práctico: Resolver el sistema:
3x + y = 9
x + 2y = 8
"""

import numpy as np

# Matriz de coeficientes (A)
A = np.array([[3, 1],
              [1, 2]])

# Vector de resultados (b)
b = np.array([9, 8])

# Resolver para x
solucion = np.linalg.solve(A, b)

print(f"La solución es x = {solucion[0]}, y = {solucion[1]}")
# Salida: La solución es x = 2.0, y = 3.0

La solución es x = 2.0, y = 3.0


**<p style="font-size:18px; color:auto;">4. En Ciencia de Datos y Machine Learning</p>**

Casi todas las operaciones en estas áreas se basan en matrices:

* Normalizar o escalar características de un conjunto de datos.
* Calcular matrices de covarianza.
* Las redes neuronales son, en esencia, una serie de multiplicaciones de matrices y funciones de activación aplicadas a los resultados.

**<p style="font-size:18px; color:auto;">5. Procesamiento de Imágenes y Gráficos</p>**
Una imagen digital puede ser representada como una matriz de píxeles (o tres matrices para los canales RGB). Aplicar filtros, cambiar el brillo, rotar o escalar una imagen son operaciones matriciales.

**<p style="font-size:18px; color:auto;">¿Cuándo NO es tan práctico?</p>**

* Cuando los datos no son homogéneos: Si tienes una colección de datos con tipos mixtos (números, textos, objetos, etc.), una lista de diccionarios de Python es una estructura mucho más adecuada. Las matrices de NumPy requieren que todos los elementos sean del mismo tipo de dato (ej. int64 o float64).
* Cuando la lógica por elemento es muy compleja y no es matemática: Si para cada elemento necesitas aplicar una serie de condiciones if/elif/else complejas que no se pueden expresar fácilmente como una fórmula matemática, un bucle for tradicional puede ser más claro y directo.
* Para colecciones de datos muy pequeñas y simples: Si solo tienes un puñado de números, el overhead de importar y usar NumPy puede ser innecesario.



**<p style="font-size:18px; color:auto;">Otros Ejemplos</p>**

**<p style="font-size:18px; color:auto;">Ejemplo 1: Procesamiento de Imágenes - Aumentar el Brillo</p>**

**Problema:** Una imagen en escala de grises puede representarse como una matriz donde cada elemento es un valor de píxel (ej. de 0 a 255). Queremos aumentar el brillo de toda la imagen de forma uniforme.

**Lógica:** Simplemente sumamos un valor constante a cada píxel. Con NumPy, esto es una sola operación.


In [6]:
import numpy as np

# Creamos una matriz que simula una imagen pequeña de 4x4 píxeles
imagen = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])

# Factor de brillo que queremos añadir
factor_brillo = 50

# Aumentamos el brillo de TODOS los píxeles a la vez
imagen_aclarada = imagen + factor_brillo

# Nos aseguramos de que ningún píxel supere el valor máximo (255)
# np.clip es una función que limita los valores a un rango [min, max]
imagen_aclarada = np.clip(imagen_aclarada, 0, 255)

print("--- Imagen Original ---")
print(imagen)

print("\n--- Imagen Aclarada ---")
print(imagen_aclarada)

--- Imagen Original ---
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]

--- Imagen Aclarada ---
[[ 60  70  80  90]
 [100 110 120 130]
 [140 150 160 170]
 [180 190 200 210]]


**Ventaja Práctica:** En lugar de usar dos bucles for anidados para recorrer cada píxel (lo cual sería muy lento en una imagen real de millones de píxeles), realizamos la operación en toda la matriz de una sola vez. Es extremadamente rápido y el código es muy legible.

**<p style="font-size:18px; color:auto;">Ejemplo 2: Análisis de Datos - Normalización de Datos (Z-score)</p>**

**Problema:** Tienes las calificaciones de un grupo de estudiantes y quieres saber qué tan bien o mal le fue a cada uno en relación con el promedio de la clase. Para esto, se usa la normalización Z-score, cuya fórmula es: z = (x - media) / desviación_estándar.

**Lógica:** Con NumPy, podemos calcular la media y la desviación estándar de todo el grupo y luego aplicar la fórmula a todas las calificaciones simultáneamente.

In [7]:
import numpy as np

# Calificaciones de 10 estudiantes
calificaciones = np.array([85, 92, 78, 65, 95, 88, 76, 89, 91, 80])

# 1. Calcular la media y la desviación estándar
media = np.mean(calificaciones)
desviacion_std = np.std(calificaciones)

# 2. Aplicar la fórmula a todo el arreglo a la vez
calificaciones_normalizadas = (calificaciones - media) / desviacion_std

print("--- Calificaciones Originales ---")
print(calificaciones)

print(f"\nMedia de la clase: {media:.2f}")
print(f"Desviación Estándar: {desviacion_std:.2f}")

print("\n--- Calificaciones Normalizadas (Z-scores) ---")
# El Z-score indica cuántas desviaciones estándar por encima o por debajo
# de la media está cada calificación.
print(calificaciones_normalizadas)

--- Calificaciones Originales ---
[85 92 78 65 95 88 76 89 91 80]

Media de la clase: 83.90
Desviación Estándar: 8.68

--- Calificaciones Normalizadas (Z-scores) ---
[ 0.1267722   0.9335044  -0.67996    -2.17817694  1.27924677  0.47251457
 -0.91045491  0.58776203  0.81825695 -0.44946508]


**Ventaja Práctica:** Realizamos un cálculo estadístico complejo sobre un conjunto de datos completo con una sola línea de código, evitando bucles manuales y haciendo el código muy fácil de leer y verificar.

**<p style="font-size:18px; color:auto;">Ejemplo 3: Finanzas y Negocios - Cálculo de Ingresos Totales</p>**

**Problema:** Tienes un registro de las cantidades vendidas de varios productos y sus respectivos precios. Quieres calcular el ingreso total de las ventas.

**Lógica:** El ingreso total es la suma de (cantidad_producto_1 * precio_1) + (cantidad_producto_2 * precio_2) + ... Esto es exactamente la definición de un producto punto (dot product) entre dos vectores.

In [9]:
import numpy as np

# Vector con las cantidades vendidas de 4 productos
cantidades = np.array([10, 25, 8, 30])

# Vector con los precios de cada producto
precios = np.array([1500, 800, 3500, 2200]) # Precios en CLP

# Calculamos el ingreso total con un producto punto
ingreso_total = np.dot(cantidades, precios)

print("--- Datos de Ventas ---")
print(f"Cantidades vendidas: {cantidades}")
print(f"Precios unitarios: {precios}")

print("\n--- Resultado ---")
print(f"El ingreso total por ventas es: ${ingreso_total} CLP")

--- Datos de Ventas ---
Cantidades vendidas: [10 25  8 30]
Precios unitarios: [1500  800 3500 2200]

--- Resultado ---
El ingreso total por ventas es: $129000 CLP


**Ventaja Práctica:** El np.dot() es una operación fundamental del álgebra lineal que representa perfectamente este tipo de problemas. Es mucho más expresivo y eficiente que un bucle for que acumula la suma de las multiplicaciones.

**<p style="font-size:18px; color:auto;">Ejemplo 4: Gráficos por Computadora - Rotar un Objeto 2D</p>**

**Problema:** Tienes las coordenadas de los vértices de un cuadrado y quieres rotarlo 90 grados en sentido antihorario alrededor del origen.

**Lógica:** En gráficos 2D, puedes rotar un conjunto de puntos multiplicando la matriz de puntos por una matriz de rotación.

In [10]:
import numpy as np

# Matriz de puntos [x, y]. Cada fila es un vértice del cuadrado.
puntos_cuadrado = np.array([
    [1, 1],
    [3, 1],
    [3, 3],
    [1, 3]
])

# Ángulo de rotación: 90 grados en radianes (pi / 2)
angulo = np.pi / 2
c, s = np.cos(angulo), np.sin(angulo)

# Matriz de rotación 2D
matriz_rotacion = np.array([
    [c, -s],
    [s,  c]
])

# Aplicamos la rotación multiplicando las matrices
# El símbolo @ es el operador para la multiplicación de matrices en NumPy
puntos_rotados = puntos_cuadrado @ matriz_rotacion

print("--- Vértices Originales ---")
print(puntos_cuadrado)

print("\n--- Matriz de Rotación (90°) ---")
print(matriz_rotacion)

print("\n--- Vértices Rotados ---")
# Los resultados pueden tener pequeños errores de precisión flotante (ej. 1.83e-16 en lugar de 0)
print(puntos_rotados.round(2)) # Redondeamos para una mejor visualización

--- Vértices Originales ---
[[1 1]
 [3 1]
 [3 3]
 [1 3]]

--- Matriz de Rotación (90°) ---
[[ 6.123234e-17 -1.000000e+00]
 [ 1.000000e+00  6.123234e-17]]

--- Vértices Rotados ---
[[ 1. -1.]
 [ 1. -3.]
 [ 3. -3.]
 [ 3. -1.]]


**Ventaja Práctica:** Permite aplicar transformaciones geométricas complejas a miles de puntos (como en un modelo 3D) de forma extremadamente eficiente, algo que sería prohibitivamente lento con bucles de Python.