**Resolución del Ejercicio de clase con NumPy**



In [2]:
#Primero, importamos la librería NumPy:
import numpy as np

"""
Paso 1: Crea un arreglo con np.arange y redimensionalo
Se crea un arreglo con números del 1 al 16 y luego se reestructura en una matriz de 4x4.
"""
# Crea un arreglo con números enteros del 1 al 16 (el 17 no se incluye)
arreglo_x = np.arange(1, 17)

# Redimensiona el arreglo a una matriz de 4x4
matriz_4x4 = arreglo_x.reshape(4, 4)

print("--- Paso 1 ---")
print("Matriz de 4x4 creada:")
print(matriz_4x4)


--- Paso 1 ---
Matriz de 4x4 creada:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [3]:
"""
Paso 2: Genera un arreglo con np.linspace
Se genera un arreglo que contiene 10 números flotantes, espaciados de forma uniforme entre 0 y 100.
"""

# Genera 10 números equidistantes entre 0 y 100
arreglo_linspace = np.linspace(0, 100, 10)

print("\n--- Paso 2 ---")
print("Arreglo de 10 elementos equidistantes:")
print(arreglo_linspace)



--- Paso 2 ---
Arreglo de 10 elementos equidistantes:
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [4]:
"""
Paso 3: Crea una matriz aleatoria con np.random.randint
Se crea una matriz de 3x3 con números enteros aleatorios entre 1 y 20.
"""

# Genera una matriz de 3x3 con enteros aleatorios entre 1 y 20
# (se usa 21 porque el límite superior no es inclusivo)
matriz_aleatoria_3x3 = np.random.randint(1, 21, size=(3, 3))

print("\n--- Paso 3 ---")
print("Matriz aleatoria de 3x3:")
print(matriz_aleatoria_3x3)



--- Paso 3 ---
Matriz aleatoria de 3x3:
[[ 3  9 14]
 [ 7  9 20]
 [16 12 18]]


In [6]:
"""
Paso 4: Aplica np.sqrt() y np.log()
Se aplican las funciones de raíz cuadrada y logaritmo natural a las matrices creadas.
"""

print("\n--- Paso 4 ---")

# Aplicando raíz cuadrada (sqrt)
print("\nRaíz cuadrada de la matriz 4x4:")
print(np.sqrt(matriz_4x4))

print("\nRaíz cuadrada de la matriz aleatoria 3x3:")
print(np.sqrt(matriz_aleatoria_3x3))

# Aplicando logaritmo natural (log)
print("\nLogaritmo natural de la matriz 4x4:")
print(np.log(matriz_4x4))

print("\nLogaritmo natural del arreglo linspace:")
# Nota: np.log(0) da como resultado -inf (infinito negativo) y genera una advertencia.
# Esto es matemáticamente correcto y NumPy lo maneja así.
print(np.log(arreglo_linspace))



--- Paso 4 ---

Raíz cuadrada de la matriz 4x4:
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]
 [3.60555128 3.74165739 3.87298335 4.        ]]

Raíz cuadrada de la matriz aleatoria 3x3:
[[1.73205081 3.         3.74165739]
 [2.64575131 3.         4.47213595]
 [4.         3.46410162 4.24264069]]

Logaritmo natural de la matriz 4x4:
[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665]
 [2.56494936 2.63905733 2.7080502  2.77258872]]

Logaritmo natural del arreglo linspace:
[      -inf 2.40794561 3.10109279 3.5065579  3.79423997 4.01738352
 4.19970508 4.35385576 4.48738715 4.60517019]


C:\Users\hcr88\AppData\Local\Temp\ipykernel_11056\414606816.py:22: RuntimeWarning: divide by zero encountered in log
  print(np.log(arreglo_linspace))


**<p style="font-size:18px; color:green;">Paso 5: ¿Qué diferencias notas en la forma de aplicar funciones sobre arreglos enteros vs flotantes?</p>**

La diferencia fundamental no está en cómo se aplica la función (la sintaxis es la misma: np.funcion(arreglo)), sino en el tipo de dato (dtype) del arreglo resultante.

**<p style="font-size:18px; color:auto;">Arreglos de Enteros (int):</p>**
Cuando aplicas una función matemática como np.sqrt() o np.log() a un arreglo de enteros, el resultado casi nunca es un número entero.
Para no perder precisión, NumPy crea automáticamente un nuevo arreglo de tipo flotante (float64) para almacenar los resultados.
Este cambio de tipo se llama "upcasting".

**<p style="font-size:18px; color:auto;">Arreglos de Flotantes (float):</p>**
Cuando aplicas estas mismas funciones a un arreglo que ya es de tipo flotante, el resultado seguirá siendo un arreglo de tipo flotante. No hay necesidad de cambiar el tipo de dato.


In [8]:
print("\n--- Paso 5: Diferencia de Tipos de Dato ---")

# Caso 1: Arreglo de enteros
print(f"Tipo de dato original (aleatorio): {matriz_aleatoria_3x3.dtype}")
resultado_sqrt = np.sqrt(matriz_aleatoria_3x3)
print(f"Tipo de dato después de sqrt: {resultado_sqrt.dtype}") # Cambia a float64

print("-" * 20)

# Caso 2: Arreglo de flotantes
print(f"Tipo de dato original (linspace): {arreglo_linspace.dtype}")
resultado_log = np.log(arreglo_linspace)
print(f"Tipo de dato después de log: {resultado_log.dtype}") # Se mantiene en float64


--- Paso 5: Diferencia de Tipos de Dato ---
Tipo de dato original (aleatorio): int32
Tipo de dato después de sqrt: float64
--------------------
Tipo de dato original (linspace): float64
Tipo de dato después de log: float64


C:\Users\hcr88\AppData\Local\Temp\ipykernel_11056\307907868.py:12: RuntimeWarning: divide by zero encountered in log
  resultado_log = np.log(arreglo_linspace)
