INTRODUCCION A NUMPY - Importación y Creación de Arrays

In [1]:
#Importar NumPy
import numpy as np

#Crear el primer array (vector o arreglo) con NumPy
arreglo_numerico = [1, 2, 3, 4, 5]
vector_inicial = np.array(arreglo_numerico)
print(F"El arreglo_numerico es del tipo = {type(arreglo_numerico)}")
print(F"El vector inicial es del tipo = {type(vector_inicial)}")
vector_inicial

El arreglo_numerico es del tipo = <class 'list'>
El vector inicial es del tipo = <class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [2]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(type(matriz))

#elemento = matriz[1,2]
#elemento

matriz



<class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

OPERACIONES VECTORIZADAS

In [4]:
resultado = matriz*2 #Multiplica todos los elementos por 2      resultado       matriz
resultado


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

FUNCIONES ESTADISTICAS CON NUMPHY


In [ ]:
datos = np.array([1, 2, 3, 4, 5])

media = np.mean(datos)
mediana = np.median(datos)
desviacion = np.std(datos)
minimo = np.min(datos)
maximo = np.max(datos)
suma = np.sum(datos)

print(F"Los resultados de las operaciones son: \n",
